//获取应用实例
var app = getApp();

Page({
    data: {
        class : [
            {class : "mui-icon-contact"},
            {class : "mui-icon-person"},
            {class : "mui-icon-personadd"},
            {class : "mui-icon-phone"},
            {class : "mui-icon-email"},
            {class : "mui-icon-chatbubble"},
            {class : "mui-icon-chatboxes"},
            {class : "mui-icon-weibo"},
            {class : "mui-icon-weixin"},
            {class : "mui-icon-pengyouquan"},
            {class : "mui-icon-chat"},
            {class : "mui-icon-qq"},
            {class : "mui-icon-videocam"},
            {class : "mui-icon-camera"},
            {class : "mui-icon-mic"},
            {class : "mui-icon-location"},
            {class : "mui-icon-image"},
            {class : "mui-icon-micoff"},
            {class : "mui-icon-map"},
            {class : "mui-icon-compose"},
            {class : "mui-icon-trash"},
            {class : "mui-icon-upload"},
            {class : "mui-icon-download"},
            {class : "mui-icon-close"},
            {class : "mui-icon-redo"},
            {class : "mui-icon-undo"},
            {class : "mui-icon-refresh"},
            {class : "mui-icon-star"},
            {class : "mui-icon-plus"},
            {class : "mui-icon-minus"},
            {class : "mui-icon-closeempty"},
            {class : "mui-icon-refreshempty"},
            {class : "mui-icon-starhalf"},
            {class : "mui-icon-reload"},
            {class : "mui-icon-spinner"},
            {class : "mui-icon-search"},
            {class : "mui-icon-home"},
            {class : "mui-icon-plusempty"},
            {class : "mui-icon-checkmarkempty"},
            {class : "mui-icon-forward"},
            {class : "mui-icon-navigate"},
            {class : "mui-icon-gear"},
            {class : "mui-icon-paperplane"},
            {class : "mui-icon-info"},
            {class : "mui-icon-help"},
            {class : "mui-icon-locked"},
            {class : "mui-icon-more"},
            {class : "mui-icon-flag"},
            {class : "mui-icon-settings"},
            {class : "mui-icon-list"},
            {class : "mui-icon-bars"},
            {class : "mui-icon-loop"},
            {class : "mui-icon-paperclip"},
            {class : "mui-icon-eye"},
            {class : "mui-icon-arrowup"},
            {class : "mui-icon-arrowdown"},
            {class : "mui-icon-arrowleft"},
            {class : "mui-icon-arrowright"},
            {class : "mui-icon-arrowthinup"},
            {class : "mui-icon-arrowthindown"},
            {class : "mui-icon-arrowthinleft"},
            {class : "mui-icon-arrowthinright"},
            {class : "mui-icon-pulldown"},
            {class : "mui-icon-refresh-filled"},
            {class : "mui-icon-star-filled"},
            {class : "mui-icon-personadd-filled"},
            {class : "mui-icon-contact-filled"},
            {class : "mui-icon-plus-filled"},
            {class : "mui-icon-chatboxes-filled"},
            {class : "mui-icon-minus-filled"},
            {class : "mui-icon-location-filled"},
            {class : "mui-icon-person-filled"},
            {class : "mui-icon-circle-filled"},
            {class : "mui-icon-checkbox-filled"},
            {class : "mui-icon-phone-filled"},
            {class : "mui-icon-email-filled"},
            {class : "mui-icon-chatbubble-filled"},
            {class : "mui-icon-spinner-cycle"},
            {class : "mui-icon-home-filled"},
            {class : "mui-icon-gear-filled"},
            {class : "mui-icon-info-filled"},
            {class : "mui-icon-help-filled"},
            {class : "mui-icon-more-filled"},
            {class : "mui-icon-back:before mui-icon-left-nav"},
            {class : "mui-icon-checkbox mui-icon-circle"},
            {class : "mui-icon-clear mui-icon-close-filled"},
            {class : "mui-icon-mic-filled mui-icon-speech"}
        ]
    }

});